development:
  adapter: postgresql
  encoding: unicode
  database: book_review_app_development
  username: postgres
  password: Qnhn7585
  host: localhost
  port: 5432
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: book_review_app_test
  username: postgres
  password: Qnhn7585
  host: localhost
  port: 5432
  pool: 5
